Let's try to run a tabular model with just pytorch -- having alot of issues injecting quantile regression into a fastai for some reason

In [9]:
from fastai.tabular.all import *
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupKFold
#next two lines needed to use pytorch object vs fastai
from torch.utils.data import Dataset as torch_ds 
from torch.utils.data import DataLoader as torch_dl
from torch.utils.data import Subset as torch_subset
%matplotlib inline

In [10]:
path = Path('/home/azaidi/Desktop/fastai/nbs/kaggle/osic')
Path.BASE_PATH = path
path.ls()

(#6) [Path('test.csv'),Path('train'),Path('train.csv'),Path('test'),Path('osic-pulmonary-fibrosis-progression.zip'),Path('sample_submission.csv')]

In [11]:
train_df = pd.read_csv(path/'train.csv')
sample_sub = pd.read_csv(path/'sample_submission.csv')
test_df = pd.read_csv(path/'test.csv')

In [12]:
splits = RandomSplitter(valid_pct=0.1)(range_of(train_df))
splits

((#1395) [336,509,626,160,405,1045,655,699,1358,1202...],
 (#154) [924,274,712,1261,1031,958,557,640,267,962...])

In [13]:
test_df.head()

Patient  Weeks   FVC    Percent  Age   Sex SmokingStatus
0  ID00419637202311204720264      6  3020  70.186855   73  Male     Ex-smoker
1  ID00421637202311550012437     15  2739  82.045291   68  Male     Ex-smoker
2  ID00422637202311677017371      6  1930  76.672493   73  Male     Ex-smoker
3  ID00423637202312137826377     17  3294  79.258903   72  Male     Ex-smoker
4  ID00426637202313170790466      0  2925  71.824968   73  Male  Never smoked

In [14]:
train_df

Patient  Weeks   FVC    Percent  Age   Sex  \
0     ID00007637202177411956430     -4  2315  58.253649   79  Male   
1     ID00007637202177411956430      5  2214  55.712129   79  Male   
2     ID00007637202177411956430      7  2061  51.862104   79  Male   
3     ID00007637202177411956430      9  2144  53.950679   79  Male   
4     ID00007637202177411956430     11  2069  52.063412   79  Male   
...                         ...    ...   ...        ...  ...   ...   
1544  ID00426637202313170790466     13  2712  66.594637   73  Male   
1545  ID00426637202313170790466     19  2978  73.126412   73  Male   
1546  ID00426637202313170790466     31  2908  71.407524   73  Male   
1547  ID00426637202313170790466     43  2975  73.052745   73  Male   
1548  ID00426637202313170790466     59  2774  68.117081   73  Male   

     SmokingStatus  
0        Ex-smoker  
1        Ex-smoker  
2        Ex-smoker  
3        Ex-smoker  
4        Ex-smoker  
...            ...  
1544  Never smoked  
1545  Never smoked  
1546  Never smoked  
1547  Never smoked  
1548  Never smoked  

[1549 rows x 7 columns]

In [15]:
to = TabularPandas(train_df, procs=[Categorify, Normalize],
                  cat_names = ['Patient','Sex', 'SmokingStatus'],
                  cont_names = ['Weeks', 'Age', 'Percent'],
                  y_names = 'FVC',
                  splits=splits)

In [16]:
dls = to.dataloaders(bs=12)

In [17]:
dls.show_batch()

In [18]:
learn = tabular_learner(dls, metrics=mse)
learn.fit_one_cycle(10)

In [47]:
learn.loss_func

FlattenedLoss of MSELoss()

In [19]:
learn.show_results()

In [20]:
learn.fit_one_cycle(40, lr=1e-1)

In [21]:
learn.show_results()

The predsictions actually are getting better, nice. But we need to be providing a confidence value(!!!!) as well as just predicting the FVC. The confidence value is basically the std deviation. Looks like alot of people are trying to implement this with a quantile loss function. 

Let's now implement a loss function better than MSE and see the actual metric of the competition.

Laplace Log Likelihood:

σclipped=max(σ,70)<br>
Δ=min(|FVCtrue−FVCpredicted|,1000)<br>
metric=−2‾√Δσclipped−ln(2‾√σclipped).

In [23]:
std = np.std(train_df.FVC)
std

832.5021066817243

In [24]:
actual_fvc = train_df.FVC
pred_fvc = np.mean(train_df.FVC)
pred_fvc

2690.479018721756

In [25]:
sd_clipped = np.maximum(np.std(train_df.FVC), 70)
sd_clipped

832.5021066817243

In [26]:
delta = np.abs(actual_fvc - pred_fvc) * np.sqrt(2)
delta

0       531.007521
1       673.843090
2       890.217766
3       772.838040
4       878.904057
           ...    
1544     30.435264
1545    406.616071
1546    307.621122
1547    402.373431
1548    118.116504
Name: FVC, Length: 1549, dtype: float64

In [176]:
laplace_log = np.sqrt(2) * delta / sd_clipped - np.log(np.sqrt(2) * sd_clipped)
laplace_log.sum()

-8514.043756623654

Now let's look at the quantile loss fxn we'll use

In [28]:
quantiles = (0.2, 0.5, 0.8)

In [32]:
#some hypothetical prediction of one sample for the 3 quantiles
quant_pred_fvc = (pred_fvc*0.82, pred_fvc, pred_fvc*1.23)
quant_pred_fvc

(2206.19279535184, 2690.479018721756, 3309.2891930277597)

In [34]:
for i, q in enumerate(quantiles):
    print("i is: ", i)
    print("q is: ", q)

i is:  0
q is:  0.2
i is:  1
q is:  0.5
i is:  2
q is:  0.8


In [37]:
target = actual_fvc[0]
target

2315

In [39]:
target - quant_pred_fvc

array([ 108.80720465, -375.47901872, -994.28919303])

In [40]:
error = target - quant_pred_fvc[0]
error

108.80720464816022

In [44]:
q, (q - 1) * error, q*error

(0.8, -21.76144092963204, 87.04576371852818)

In [45]:
max((q-1)* error, q*error)

87.04576371852818

In [140]:
def quantile_loss(preds, target, quantiles=(0.2, 0.5, 0.8)):
    losses = []
    for i, q in enumerate(quantiles):
        errors = target - preds[:, i]
        losses.append(torch.max((q - 1) * errors, q * errors).unsqueeze(1))
    loss = torch.mean(torch.sum(torch.cat(losses, dim=1), dim=1))
    return loss

In [148]:
??tabular_learner

In [141]:
learn = tabular_learner(dls, loss_func=quantile_loss, n_out=3)

In [142]:
learn.summary()

TabularModel (Input shape: ['12 x 3', '12 x 3'])
Layer (type)         Output Shape         Param #    Trainable 
Embedding            12 x 29              5,133      True      
________________________________________________________________
Embedding            12 x 3               9          True      
________________________________________________________________
Embedding            12 x 3               12         True      
________________________________________________________________
Dropout              12 x 35              0          False     
________________________________________________________________
BatchNorm1d          12 x 3               6          True      
________________________________________________________________
BatchNorm1d          12 x 38              76         True      
________________________________________________________________
Linear               12 x 200             7,600      True      
_________________________________________________

In [143]:
learn.fit_one_cycle(200)

In [118]:
one_batch = dls.one_batch()

In [144]:
learn.dls.test_dl(test_df)

In [145]:
test_dl = learn.dls.test_dl(test_df)

In [146]:
cat, cont, y = next(iter(test_dl))

In [147]:
learn.model(cat, cont)

tensor([[1978.3484, 2583.1653, 3253.5005],
        [2013.1833, 2614.4062, 3284.8748],
        [1967.7228, 2559.2102, 3218.0344],
        [1973.1368, 2570.3574, 3234.3755],
        [1977.9271, 2581.0354, 3250.0500]], device='cuda:0',
       grad_fn=<AddmmBackward>)

In [139]:
y

tensor([[3020],
        [2739],
        [1930],
        [3294],
        [2925]], device='cuda:0')

In [151]:
learn = tabular_learner(dls, lr=3e-3,
                        loss_func=quantile_loss, n_out=3)

In [152]:
learn.fit_one_cycle(5)

In [153]:
learn.fit_one_cycle(5, lr=3e-4)

In [154]:
learn.fit_one_cycle(10, lr=3e-5)

In [155]:
test_dl = learn.dls.test_dl(test_df)
cat, cont, y = next(iter(test_dl))
learn.model(cat, cont)

tensor([[1893.5212, 2528.6118, 3181.5300],
        [1841.6361, 2460.3394, 3107.4668],
        [1939.6361, 2604.7273, 3343.2151],
        [1858.4597, 2482.8713, 3140.6108],
        [1881.3634, 2509.9016, 3142.4504]], device='cuda:0',
       grad_fn=<AddmmBackward>)

In [156]:
y

tensor([[3020],
        [2739],
        [1930],
        [3294],
        [2925]], device='cuda:0')

In [180]:
#@staticmethod
def laplace(preds, targets):
        sigma = preds[:, 2] - preds[:, 0]
        sigma[sigma < 70] = 70
        delta = (preds[:, 1] - targets).abs()
        delta[delta > 1000] = 1000
        return (-np.sqrt(2) * delta / sigma - torch.log(np.sqrt(2) * sigma)).mean()

In [196]:
learn = tabular_learner(dls, loss_func=quantile_loss, 
                        metrics=laplace, n_out=3)

In [197]:
learn.fit_one_cycle(10)

In [192]:
def laplace_log(preds, targets):
    std = preds[:, 2] - preds[:, 0]
    std[std < 70] = 70
    delta = (preds[:, 1] - targets).abs()
    delta[delta > 1000] = 1000
    laplace = -np.sqrt(2) * delta / std - torch.log(np.sqrt(2) * std)
    return laplace.mean()

In [198]:
learn = tabular_learner(dls, loss_func=quantile_loss, 
                        metrics=laplace, n_out=3)
learn.fit_one_cycle(10)

In [199]:
to_2 = TabularPandas(train_df, procs=[Categorify, Normalize],
                  cat_names = ['Sex', 'SmokingStatus'],
                  cont_names = ['Weeks', 'Age', 'Percent'],
                  y_names = 'FVC',
                  splits=splits)
dls2 = to_2.dataloaders(bs=32)
dls2.show_batch()

In [201]:
learn = tabular_learner(dls2, loss_func=quantile_loss, 
                        metrics=laplace, n_out=3)
learn.fit_one_cycle(100)